spring:
  application:
    name: divingschool
  datasource:
    url: jdbc:sqlserver://localhost:1433;trustServerCertificate=true;databaseName=MAS
    username: ${MSSQL_DB_USERNAME}
    password: ${MSSQL_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8080

